DROP TABLE STG_CENSUS;
CREATE EXTERNAL TABLE STG_CENSUS (
        COUNTY varchar(100),
        STATE varchar(100),
        SERIES_DESC varchar(100),
        VALUE float
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t'
STORED AS TEXTFILE
LOCATION '/user/root/census_data';

DROP TABLE CENSUS;
CREATE TABLE CENSUS(
        COUNTY STRING,
        STATE STRING,
        SERIES_DESC STRING,
        VALUE FLOAT
)
COMMENT 'CENSUS Data'
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
STORED AS ORC;

INSERT OVERWRITE TABLE CENSUS
SELECT
COUNTY,
STATE,
SERIES_DESC,
VALUE
FROM STG_CENSUS;
