DROP TABLE STG_CENSUS;
CREATE EXTERNAL TABLE STG_CENSUS (
        COUNTY varchar(100),
        STATE varchar(100),
        SERIES_DESC varchar(100),
        VALUE int
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t'
STORED AS TEXTFILE
LOCATION '/user/w205/census_data';

DROP TABLE CENSUS;
CREATE TABLE CENSUS(
        COUNTY STRING,
        STATE STRING,
		JOBS_RETAIL int,
		JOBS_IT int,
		JOBS_FINANCE int,
		JOBS_RESEARCH int,
		JOBS_PUBLIC int,
		JOBS_EDUCATION int,
		JOBS_FINANCE int,
		HOUSING_COST_OWN int,
		HOUSING_COST_RENT int,
		POP_TOT int,
		POP_YOUNG int
)
COMMENT 'CENSUS Data'
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
STORED AS ORC;

INSERT OVERWRITE TABLE CENSUS
SELECT
	COUNTY,
	STATE,
	MAX(CASE 
		WHEN SERIES_DESC = "jobs_retail" THEN VALUE
		ELSE 0
	END) AS jobs_retail,
	MAX(CASE 
		WHEN SERIES_DESC = "jobs_it" THEN VALUE
		ELSE 0
	END) AS jobs_it,
	MAX(CASE 
		WHEN SERIES_DESC = "jobs_finance" THEN VALUE
		ELSE 0
	END) AS jobs_finance,
	MAX(CASE 
		WHEN SERIES_DESC = "job_research" THEN VALUE
		ELSE 0
	END) AS jobs_research,
	MAX(CASE 
		WHEN SERIES_DESC = "jobs_public" THEN VALUE
		ELSE 0
	END) AS jobs_public,
	MAX(CASE 
		WHEN SERIES_DESC = "jobs_education" THEN VALUE
		ELSE 0
	END) AS jobs_education,
	MAX(CASE 
		WHEN SERIES_DESC = "jobs_finance" THEN VALUE
		ELSE 0
	END) AS jobs_finance,
	MAX(CASE 
		WHEN SERIES_DESC = "housing_cost_own" THEN VALUE
		ELSE 0
	END) AS housing_cost_own,
	MAX(CASE 
		WHEN SERIES_DESC = "housing_cost_rent" THEN VALUE
		ELSE 0
	END) AS housing_cost_rent,
	MAX(CASE 
		WHEN SERIES_DESC = "pop_tot" THEN VALUE
		ELSE 0
	END) AS pop_tot,
	SUM(CASE 
		WHEN SERIES_DESC = "pop_20_24" THEN VALUE
		WHEN SERIES_DESC = "pop_25_34" THEN VALUE
		ELSE 0
	END) AS pop_young
FROM STG_CENSUS
GROUP BY COUNTY,STATE;
