DROP TABLE STG_INDEED;
CREATE EXTERNAL TABLE STG_INDEED (
	JOBKEY varchar(100),
	JOBTITLE varchar(100),
	COMPANY varchar(100),
	SNIPPET varchar(500),
	URL varchar(500),
	DATE varchar(100),
	CITY varchar(100),
	COUNTY varchar(100),
	STATE varchar(100),
    LATITUDE float,
    LONGITUDE float
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY '\t'
STORED AS TEXTFILE
LOCATION '/user/w205/indeed_data';

DROP TABLE INDEED;
CREATE TABLE INDEED(
	JOBKEY STRING,
	JOBTITLE STRING,
	COMPANY STRING,
	SNIPPET STRING,
	URL STRING,
	DATE STRING,
	CITY STRING,
	COUNTY STRING,
	STATE STRING,
    LATITUDE float,
    LONGITUDE float
)
COMMENT 'INDEED Data'
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
STORED AS ORC;

INSERT OVERWRITE TABLE INDEED
SELECT * FROM STG_INDEED
