
DROP TABLE PERCENTILES;
CREATE TABLE PERCENTILES(
	P85_HOUSING_COST_OWN float,
	P85_HOUSING_COST_RENT float,
	P85_JOBS_RETAIL_PER_YOUNG float,
	P85_JOBS_IT_PER_YOUNG float,
	P85_JOBS_FINANCE_PER_YOUNG float,
	P85_JOBS_RESEARCH_PER_YOUNG float,
	P85_JOBS_PUBLIC_PER_YOUNG float,
	P85_JOBS_EDUCATION_PER_YOUNG float
)
COMMENT '85th Percentile Cutoff Values'
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
STORED AS ORC;

INSERT OVERWRITE TABLE PERCENTILES
SELECT
	PERCENTILE_APPROX(HOUSING_COST_OWN,0.15) as P85_HOUSING_COST_OWN,
	PERCENTILE_APPROX(HOUSING_COST_RENT,0.15) as P85_HOUSING_COST_RENT,
	PERCENTILE_APPROX(JOBS_RETAIL/POP_YOUNG,0.85) as P85_JOBS_RETAIL_PER_YOUNG,
	PERCENTILE_APPROX(JOBS_IT/POP_YOUNG,0.85) as P85_JOBS_IT_PER_YOUNG,
	PERCENTILE_APPROX(JOBS_FINANCE/POP_YOUNG,0.85) as P85_JOBS_FINANCE_PER_YOUNG,
	PERCENTILE_APPROX(JOBS_RESEARCH/POP_YOUNG,0.85) as P85_JOBS_RESEARCH_PER_YOUNG,
	PERCENTILE_APPROX(JOBS_PUBLIC/POP_YOUNG,0.85) as P85_JOBS_PUBLIC_PER_YOUNG,
	PERCENTILE_APPROX(JOBS_EDUCATION/POP_YOUNG,0.85) as P85_JOBS_EDUCATION_PER_YOUNG
FROM CENSUS;

DROP TABLE TOP_COUNTIES;
CREATE TABLE TOP_COUNTIES(
        COUNTY STRING,
        STATE STRING,
		JOBS_RETAIL FLOAT,
		TOP_RETAIL INT,
		JOBS_IT FLOAT,
		TOP_IT INT,
		JOBS_FINANCE FLOAT,
		TOP_FINANCE INT,
		JOBS_RESEARCH FLOAT,
		TOP_RESEARCH INT,
		JOBS_PUBLIC FLOAT,
		TOP_PUBLIC INT,
		JOBS_EDUCATION FLOAT,
		TOP_EDUCATION INT,
		HOUSING_COST_OWN FLOAT,
		HOUSING_COST_RENT FLOAT,
		POP_TOT INT,
		POP_YOUNG INT
)
COMMENT 'TOP COUNTY DATA'
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
STORED AS ORC;

INSERT OVERWRITE TABLE TOP_COUNTIES
SELECT
	COUNTY,
	STATE,
	JOBS_RETAIL,
	CASE
		WHEN JOBS_RETAIL/POP_YOUNG >= P85_JOBS_RETAIL_PER_YOUNG AND HOUSING_COST_OWN <= P85_HOUSING_COST_OWN THEN 1
		WHEN JOBS_RETAIL/POP_YOUNG >= P85_JOBS_RETAIL_PER_YOUNG AND HOUSING_COST_RENT <= P85_HOUSING_COST_RENT THEN 1
		ELSE 0
	END AS TOP_RETAIL,
	JOBS_IT,
	CASE
		WHEN JOBS_IT/POP_YOUNG >= P85_JOBS_IT_PER_YOUNG AND HOUSING_COST_OWN <= P85_HOUSING_COST_OWN THEN 1
		WHEN JOBS_IT/POP_YOUNG >= P85_JOBS_IT_PER_YOUNG AND HOUSING_COST_RENT <= P85_HOUSING_COST_RENT THEN 1
		ELSE 0
	END AS TOP_IT,
	JOBS_FINANCE,
	CASE
		WHEN JOBS_FINANCE/POP_YOUNG >= P85_JOBS_FINANCE_PER_YOUNG AND HOUSING_COST_OWN <= P85_HOUSING_COST_OWN THEN 1
		WHEN JOBS_FINANCE/POP_YOUNG >= P85_JOBS_FINANCE_PER_YOUNG AND HOUSING_COST_RENT <= P85_HOUSING_COST_RENT THEN 1
		ELSE 0
	END AS TOP_FINANCE,
	JOBS_RESEARCH,
	CASE
		WHEN JOBS_RESEARCH/POP_YOUNG >= P85_JOBS_RESEARCH_PER_YOUNG AND HOUSING_COST_OWN <= P85_HOUSING_COST_OWN THEN 1
		WHEN JOBS_RESEARCH/POP_YOUNG >= P85_JOBS_RESEARCH_PER_YOUNG AND HOUSING_COST_RENT <= P85_HOUSING_COST_RENT THEN 1
		ELSE 0
	END AS TOP_RESEARCH,
	JOBS_PUBLIC,
	CASE
		WHEN JOBS_PUBLIC/POP_YOUNG >= P85_JOBS_PUBLIC_PER_YOUNG AND HOUSING_COST_OWN <= P85_HOUSING_COST_OWN THEN 1
		WHEN JOBS_PUBLIC/POP_YOUNG >= P85_JOBS_PUBLIC_PER_YOUNG AND HOUSING_COST_RENT <= P85_HOUSING_COST_RENT THEN 1
		ELSE 0
	END AS TOP_PUBLIC,
	JOBS_EDUCATION,
	CASE
		WHEN JOBS_EDUCATION/POP_YOUNG >= P85_JOBS_EDUCATION_PER_YOUNG AND HOUSING_COST_OWN <= P85_HOUSING_COST_OWN THEN 1
		WHEN JOBS_EDUCATION/POP_YOUNG >= P85_JOBS_EDUCATION_PER_YOUNG AND HOUSING_COST_RENT <= P85_HOUSING_COST_RENT THEN 1
		ELSE 0
	END AS TOP_EDUCATION,
	HOUSING_COST_OWN,
	HOUSING_COST_RENT,
	POP_TOT,
	POP_YOUNG
	
FROM CENSUS t1
INNER JOIN PERCENTILES t2
on 1=1
;